Repository DanGravel/SYSC4806, pull requests merged in 2019-03, with the labels that each got.

#15 #14 Made some bug fixes
  Project/src/main/java/app/FileRepository.java
  Project/src/main/java/app/FileUploadController.java
  Project/src/main/java/app/models/File.java
  Project/src/main/java/app/models/User.java
  Project/src/main/resources/templates/upload.html
Labels: bug, enhancement

#46 #45 and #34 Fixed file size issue, page doesn't break now.
  Project/src/main/resources/application.properties
  Project/src/main/resources/static/js/upload.js
  Project/src/main/resources/templates/upload.html
Labels: bug

#76 Taz/add nav bar
  Project/src/main/resources/templates/default.html
  Project/src/main/resources/templates/editor.html
  Project/src/main/resources/templates/header.html
  Project/src/main/resources/templates/review.html
  Project/src/main/resources/templates/reviewer.html
  Project/src/main/resources/templates/upload.html
  Project/target/classes/templates/default.html
Labels: enhancement

#74 Updated editor to bootstrap
  Project/src/main/resources/templates/editor.html
Labels: enhancement

#75 #44 Added error pages
  Project/src/main/resources/static/css/error.css
  Project/src/main/resources/templates/error/403.html
  Project/src/main/resources/templates/error/404.html
  Project/src/main/resources/templates/error/500.html
Labels: enhancement

#71 Taz/add reviewer fix
  Project/src/main/java/app/Application.java
  Project/src/main/java/app/EditorController.java
  Project/src/main/java/app/models/Article.java
  Project/src/main/resources/templates/editor.html
Labels: enhancement

#72 Home page is now respective to each role
  Project/src/main/java/app/RegisterController.java
  Project/src/main/resources/templates/default.html
  Project/target/classes/templates/default.html
Labels: enhancement

#96 Taz/due date picker
  Project/pom.xml
  Project/src/main/java/app/EditorController.java
  Project/src/main/java/app/models/Article.java
  Project/src/main/resources/static/js/editor.js
  Project/src/main/resources/static/js/editorTableSort.js
  Project/src/main/resources/templates/editor.html
Labels: enhancement

#98 Added row highlighting if review is overdue
  Project/src/main/java/app/models/Article.java
  Project/src/main/resources/templates/editor.html
Labels: enhancement

#121 Updated all dependencies
  Project/pom.xml
  Project/src/main/resources/templates/editor.html
  Project/src/main/resources/templates/header.html
  Project/src/main/resources/templates/login.html
  Project/src/main/resources/templates/register.html
  Project/src/main/resources/templates/review.html
  Project/src/main/resources/templates/reviewer.html
  Project/src/main/resources/templates/upload.html
Labels: enhancement

#126 Update login.html
  Project/src/main/resources/templates/login.html
Labels: bug

#128 #127 Change register redirect to default url
  Project/src/main/java/app/RegisterController.java
Labels: enhancement

#123 #91 Changed stuff to bootstrap uploader and has desired behaviour now
  Project/src/main/resources/static/css/upload.css
  Project/src/main/resources/static/js/upload.js
  Project/src/main/resources/templates/upload.html
Labels: bug

#132 Added unit tests
  Project/src/main/java/app/EditorController.java
  Project/src/test/java/app/EditorTest.java
Labels: enhancement

#152 Daniel/redirect test
  Project/src/test/java/app/BaseTest.java
Labels: enhancement

#150 #149 Moved login and base url controller logic to their own classes
  Project/src/main/java/app/BaseController.java
  Project/src/main/java/app/LoginController.java
  Project/src/main/java/app/RegisterController.java
Labels: enhancement

#163 #161 Added some tests for the article model
  Project/src/main/java/app/models/Article.java
  Project/src/main/java/app/models/User.java
  Project/src/test/java/app/ArticleTest.java
Labels: enhancement
